import {
  signInWithCustomToken,
  signOut,
  onAuthStateChanged,
  User,
  signInWithEmailAndPassword,
} from '@firebase/auth';
import * as vscode from 'vscode';
import { getFirebaseAuth } from '../firebase/client';

const SECRET_KEY = 'msdev.firebaseToken';

export class AuthManager {
  private _context: vscode.ExtensionContext;
  private _currentUser: User | null = null;
  private _onAuthChange: ((user: User | null) => void) | null = null;

  constructor(context: vscode.ExtensionContext) {
    this._context = context;
  }

  get currentUser(): User | null {
    return this._currentUser;
  }

  onAuthStateChange(callback: (user: User | null) => void) {
    this._onAuthChange = callback;
  }

  /** Try to restore a persisted session silently on extension startup */
  async restoreSession(): Promise<User | null> {
    try {
      const auth = getFirebaseAuth();
      return new Promise((resolve) => {
        const unsub = onAuthStateChanged(auth, (user) => {
          unsub();
          this._currentUser = user;
          this._onAuthChange?.(user);
          resolve(user);
        });
      });
    } catch {
      return null;
    }
  }

  /** Sign in with a custom token generated by the web app */
  async loginWithCustomToken(): Promise<User | null> {
    const token = await vscode.window.showInputBox({
      title: 'MSDEV: Sign In',
      prompt: 'Paste your VS Code Connect Token from the MSDEV web app (Profile → Connect VS Code)',
      password: false,
      placeHolder: 'Paste token here...',
      ignoreFocusOut: true,
    });

    if (!token?.trim()) {
      return null;
    }

    try {
      const auth = getFirebaseAuth();
      const credential = await signInWithCustomToken(auth, token.trim());
      this._currentUser = credential.user;

      // Persist the UID so we can re-auth on next launch
      await this._context.secrets.store(SECRET_KEY, token.trim());

      this._onAuthChange?.(credential.user);
      vscode.window.showInformationMessage(`✅ MSDEV: Signed in as ${credential.user.displayName || credential.user.email}`);
      return credential.user;
    } catch (err: any) {
      vscode.window.showErrorMessage(`MSDEV Sign In failed: ${err.message}`);
      return null;
    }
  }

  /** Fallback: sign in with email + password */
  async loginWithEmail(): Promise<User | null> {
    const email = await vscode.window.showInputBox({
      title: 'MSDEV: Sign In — Email',
      prompt: 'Enter your MSDEV email address',
      placeHolder: 'you@example.com',
      ignoreFocusOut: true,
    });
    if (!email?.trim()) return null;

    const password = await vscode.window.showInputBox({
      title: 'MSDEV: Sign In — Password',
      prompt: 'Enter your MSDEV password',
      password: true,
      ignoreFocusOut: true,
    });
    if (!password) return null;

    try {
      const auth = getFirebaseAuth();
      const credential = await signInWithEmailAndPassword(auth, email.trim(), password);
      this._currentUser = credential.user;
      this._onAuthChange?.(credential.user);
      vscode.window.showInformationMessage(`✅ MSDEV: Signed in as ${credential.user.displayName || credential.user.email}`);
      return credential.user;
    } catch (err: any) {
      vscode.window.showErrorMessage(`MSDEV Sign In failed: ${err.message}`);
      return null;
    }
  }

  async logout(): Promise<void> {
    try {
      const auth = getFirebaseAuth();
      await signOut(auth);
      this._currentUser = null;
      await this._context.secrets.delete(SECRET_KEY);
      this._onAuthChange?.(null);
      vscode.window.showInformationMessage('MSDEV: Signed out.');
    } catch (err: any) {
      vscode.window.showErrorMessage(`MSDEV Sign Out failed: ${err.message}`);
    }
  }
}
