// File generated by FlutterFire CLI & Antigravity.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEImX1yeZ_QC0BH034SJIEoOB_GNPrt_4',
    appId: '1:332300816650:web:8fa0340c901b6a00feaaf3',
    messagingSenderId: '332300816650',
    projectId: 'msdev-msdev',
    authDomain: 'msdev-msdev.firebaseapp.com',
    storageBucket: 'msdev-msdev.firebasestorage.app',
    measurementId: 'G-VL7SW4J2KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEImX1yeZ_QC0BH034SJIEoOB_GNPrt_4',
    appId: '1:332300816650:android:8fa0340c901b6a00feaaf3',
    messagingSenderId: '332300816650',
    projectId: 'msdev-msdev',
    storageBucket: 'msdev-msdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEImX1yeZ_QC0BH034SJIEoOB_GNPrt_4',
    appId: '1:332300816650:ios:8fa0340c901b6a00feaaf3',
    messagingSenderId: '332300816650',
    projectId: 'msdev-msdev',
    storageBucket: 'msdev-msdev.firebasestorage.app',
    iosBundleId: 'com.example.msdevMobile',
  );
}
